#!/bin/bash

blog=/absolute/path/to/jekyll-site/source  ## CHANGE THIS FOR YOUR INSTALL
now=$(date +"%Y-%m-%d")
title=$1
post=$blog/_posts/$now-$title.markdown

echo "Categories?"
read categories

echo "Excerpt?"
read excerpt

echo "Comment?"
read comment

echo "Link Title?"
read linktitle

echo "Link URL?"
read linkurl

touch $post
echo "---
layout: default
title: \"$1\"
published: true
comments: true
categories: [Posts, $categories]
---
$comment

> $excerpt

[$linktitle]($linkurl)" >> $post
sublime $post
